## Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_ejemplo
spring.datasource.username=postgres
spring.datasource.password=44355q6DfqrdQ
spring.datasource.driver-class-name=org.postgresql.Driver

## Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

## Puerto del servidor
server.port=8080

## Nombre de la aplicación
spring.application.name=ApiRestJPA
